logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    fr.poc.airbnb: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: airbnb_db
  liquibase:
    contexts: prod
    default-schema: airbnb_db